# assignment solution (coding section)

# Name : Amr Eid Mohamed Hanafy AbdElGawad

# Group :5

### (1) Calculating the inverse of a 2x2 matrix without using numpy


In [87]:
# Code a function to calculate the determinant of 2x2 matrix
#i dont use np.linalg.det built it from scratch

A=[[1,2]
  ,[3,4]]

def calc_determinant(A):
    det_A=(A[0][0]*A[1][1])-(A[0][1]*A[1][0])
    return (det_A)

print("Determinant of a 2x2 matrix is :",calc_determinant(A))

Determinant of a 2x2 matrix is : -2


In [88]:
# Code a function that interchange the diagonal elements of
# a 2x2 matrix and inverse the sign of the off diagonal elements

def sign_inv(A):
    A[0][0],A[1][1]=A[1][1],A[0][0]
    A[0][1]=-A[0][1]
    A[1][0]=-A[1][0]
    return (A)

print (sign_inv(A))

[[4, -2], [-3, 1]]


In [108]:
#Code a function to compute the inverse of 2x2 matrix based on the two previous functions if it exists
A=[[1,2]
  ,[3,6]]

B=[[1,2]
  ,[3,4]]
def compute_inv(A):
    det_A=calc_determinant(A)
    A_adj=sign_inv(A)
    A_inv=[[0,0],[0,0]]
    try:
        for i in range(len(A[0])):
            for j in range (len(A[1])):
                A_inv[i][j]=A_adj[i][j]/det_A
    except:
        print("inverse not existed -------> Division by Zero \n")
    
    return(A_inv)


print (compute_inv(A),"\n\n")
print ("inverse B :",compute_inv(B))

inverse not existed -------> Division by Zero 

[[0, 0], [0, 0]] 


inverse B : [[-2.0, 1.0], [1.5, -0.5]]


### (2) Coding a Python code to inverse a 3x3 matrix in order to solve a linear system (no numpy.linalg.inv allowed) with 3 constraints and 3 variables:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [23]:
#Coding a function that checks if a 3x3 matrix is invertible
A1=np.array([[1,2,3]
            ,[4,5,6]
            ,[7,8,9]])

B=np.array([[1,2,3]
           ,[4,2,6]
           ,[7,8,9]])

def calc_determinant(A):
    tmp=[]
    for j in range(len(A[0,:])):
        Atemp=np.delete(A,j,1)          #delete row of selected element
        Atemp=np.delete(Atemp,0,0)      #delete column of selected element
        minor=(A[0][j]*((Atemp[0][0]*Atemp[1][1])-(Atemp[0][1]*Atemp[1][0])))
        tmp.append(minor)
    tmp[1]=-tmp[1]  # to make it add first then subtract the second then add the third basedd on co factors
    return (sum(tmp))

def invertible_check(x):
    det=calc_determinant(x)

    if det==0:
        print("matrix is not invertible ------> determinant is zero")
    else :
        print("matrix is invertible ---------->  determinant is : " ,det)
invertible_check(A1)
invertible_check(B)


matrix is not invertible ------> determinant is zero
matrix is invertible ---------->  determinant is :  36


In [29]:
#Coding a function that generates the transpose of a 3x3 matrix
A2=np.array([[1,2,3]
  ,[4,5,6]
   ,[7,8,9]])


def transpose(A):
    A_trans=np.zeros([3,3])
    for i in range(len(A[0,:])):
        for j in range(len(A[:,1])):
            A_trans[i][j]=A[j][i]
    return(A_trans)


transpose(A2)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [40]:
#Coding a function that generates the matrix of minors of a 3x3 matrix

A3=np.array([[1,2,3]
  ,[4,2,1]
   ,[7,8,9]])

def arr_minors(A):
    A_minors=np.zeros([3,3])
    for i in range(len(A[:,0])):
        for j in range(len(A[0,:])):
            Atemp=np.delete(A,j,1)          #delete row of selected element
            Atemp=np.delete(Atemp,i,0)      #delete column of selected element
            minor=((Atemp[0][0]*Atemp[1][1])-(Atemp[0][1]*Atemp[1][0]))
            A_minors[i][j]=minor
    return(A_minors)

A4=arr_minors(A3)

print(A4)

[[ 10.  29.  18.]
 [ -6. -12.  -6.]
 [ -4. -11.  -6.]]


In [41]:
# Coding a function that generates the matrix of cofactors of a 3x3 matrix

def cofactor(A):
    arr=np.array([[1,-1,1]   #array of cofactors
         ,[-1,1,-1]
         ,[1,-1,1]])

    return (A*arr)


cofactor(A4)
    

array([[ 10., -29.,  18.],
       [  6., -12.,   6.],
       [ -4.,  11.,  -6.]])

In [44]:
# Coding a function that generates the inverse of a 3x3 matrix if it exists
A5=np.array([[1,2,3]
           ,[4,2,1]
           ,[7,8,9]])
def inv(X):
    det=calc_determinant(X)  #determinant of matrix
    X=arr_minors(X)    #array of minors
    X=cofactor(X)# cofactors
    X=transpose(X) #transpose
    X=X/det  #divide adjucate matrix by the determinant
    return(X)

inv(A5)

array([[ 1.66666667,  1.        , -0.66666667],
       [-4.83333333, -2.        ,  1.83333333],
       [ 3.        ,  1.        , -1.        ]])